# Configuration file for Luminos.     http://luminos.menteslibres.org
#
# You are viewing a YAML formatted file, read more about the format
# at http://www.yaml.org.
#
# Notes:
# - Use two space indentations instead of the \t character.
# - Left-side elements must start with a Capital letter to be available in
#   the template as e.g. {{ .Site.Page.Body.Title }}
# - Settings not references in pages are lowercase

searchindex: "/tmp/lumex-search.cdb"

Page:
  # Name of the site.
  Brand: "Luminos"

  # Some properties for <head>.
  Head:
    # Title that appears on the <title> tag.
    Title: "Luminos markdown server."

  # Some properties for <body>.
  Body:
    # Page subtitle.
    Title: "Markdown server"

    # Top navigation bar.
    Menu:
      - { Text: "Download Luminos", URL: "https://github.com/lnxjedi/luminos/releases" }

    # Top-right navigation helper.
    MenuPull:
      - { Text: "Home", URL: "/" }

    Copyright: "&copy; 2012-2014. J. Carlos Nieto. / 2018 David L. Parsley"
